{% set version = "2.0-0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mlogit
  version: "{{ version|replace("-", "_") }}"

source:
  url:
    - {{ cran_mirror }}/src/contrib/mlogit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mlogit/mlogit_{{ version }}.tar.gz
  sha256: 0ae2768408f557fa6a4b09c56ca4d03fe1f580fb256ab9eecd9ee04b858a9475

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-formula
    - r-rdpack
    - r-dfidx
    - r-lmtest
    - r-micsr
    - r-numderiv
  run:
    - r-base
    - r-formula
    - r-rdpack
    - r-dfidx
    - r-lmtest
    - r-micsr
    - r-numderiv

test:
  commands:
    - $R -e "library('mlogit')"           # [not win]
    - "\"%R%\" -e \"library('mlogit')\""  # [win]

about:
  home: https://cran.r-project.org/package=mlogit
  license: GPL-2.0-or-later
  summary: Maximum likelihood estimation of random utility discrete choice models. The software
    is described in Croissant (2020) <doi:10.18637/jss.v095.i11> and the underlying
    methods in Train (2009) <doi:10.1017/CBO9780511805271>.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - nsoranzo
