{% set version = "1.1-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mlogit
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mlogit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mlogit/mlogit_{{ version }}.tar.gz
  sha256: 6f3ea97db410be929a3078422f3d354d2f17855a21bbdc7c2c09d901e233d143

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dfidx
    - r-formula
    - r-mass
    - r-rdpack
    - r-lmtest
    - r-statmod
    - r-zoo
  run:
    - r-base
    - r-dfidx
    - r-formula
    - r-mass
    - r-rdpack
    - r-lmtest
    - r-statmod
    - r-zoo

test:
  commands:
    - $R -e "library('mlogit')"           # [not win]
    - "\"%R%\" -e \"library('mlogit')\""  # [win]

about:
  home: https://cran.r-project.org/package=mlogit, https://r-forge.r-project.org/projects/mlogit/
  license: GPL-2.0-or-later
  summary: Maximum Likelihood estimation of random utility discrete choice models, as described in Kenneth Train (2009) Discrete Choice Methods with Simulations <doi:10.1017/CBO9780511805271>.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - nsoranzo
