{% set version = '0.4-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mlogit
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mlogit_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mlogit/mlogit_{{ version }}.tar.gz
  sha256: bf8fb55f2591b54c059c8b7359149ce1b5c80535074f22924c00672a08ea0070

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-formula
    - r-mass
    - r-rdpack
    - r-lmtest
    - r-statmod
    - r-zoo
  run:
    - r-base
    - r-formula
    - r-mass
    - r-rdpack
    - r-lmtest
    - r-statmod
    - r-zoo

test:
  commands:
    - $R -e "library('mlogit')"           # [not win]
    - "\"%R%\" -e \"library('mlogit')\""  # [win]

about:
  home: https://cran.r-project.org/package=mlogit, https://r-forge.r-project.org/projects/mlogit/
  license: GPL (>= 2)
  summary: Maximum Likelihood estimation of random utility discrete choice models (logit and
    probit).
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - nsoranzo

# Package: mlogit
# Version: 0.4-1
# Date: 2019-02-01
# Title: Multinomial Logit Models
# Authors@R: person("Yves", "Croissant", role = c("aut", "cre"), email = "yves.croissant@univ-reunion.fr")
# Depends: R (>= 2.10), Formula, zoo, lmtest
# Imports: statmod, MASS, Rdpack
# Suggests: knitr, car, nnet, lattice, AER, ggplot2, texreg, rmarkdown
# Description: Maximum Likelihood estimation of random utility discrete choice models (logit and probit).
# VignetteBuilder: knitr
# Encoding: UTF-8
# License: GPL (>= 2)
# URL: https://cran.r-project.org/package=mlogit, https://r-forge.r-project.org/projects/mlogit/
# RoxygenNote: 6.1.1
# RdMacros: Rdpack
# Author: Yves Croissant [aut, cre]
# Maintainer: Yves Croissant <yves.croissant@univ-reunion.fr>
# Repository: CRAN
# Repository/R-Forge/Project: mlogit
# Repository/R-Forge/Revision: 76
# Repository/R-Forge/DateTimeStamp: 2019-02-01 15:41:09
# Date/Publication: 2019-02-01 22:10:03 UTC
# NeedsCompilation: no
# Packaged: 2019-02-01 15:54:42 UTC; rforge
