travis:
  secure:
    BINSTAR_TOKEN: ae0fZSG0/0BhUf5wgWcV+4y0TagWEjUzGaXQa5SstumB8TRHZvGfRxylJqXSOKKCKAH9XBYdUg/FGN/0ntf67sQNgXfJciZu/M4Gz9oATltgB6hv95mlbqkKgejNVpo01pbktQ7GEkeBD0giZyr+6Y2rDm1BiGqb3OFYSGjj7m/p1qRTxqThRMjzA9bHKEhpRfVfQarfsBk65bmaR/+Egz+uTINwxMgeBipBH1WSE9/QxuJWsMBAG0vUOGcf3tIYdgmiMyXlp/zvYWVdl2vmDntjY9b5tdsR59gpoC90WyncdtakA2q8RvzxXT9KbOvG6Yuwigkdm6VMAHVSg/VbzdBCaYUQQPrZ0ZuXFGzu0VirTlcMIwfnSjiDU06PpG6mzc6Rlj1XIBummbIXnBmaNd25/4fqRfTEQhbqq9pirsT1p54nejxHbI5UnWNWWw7xtgIg4kCXVp700s5jIE7kJZHHFJHitsRHb4T/ztJ24h6V7UwgXBMHhlQqM2mPBPBAV91LLnYwHA5vfnIdCh19DwmSk5psFPHE4Wx2KZhJH+2c6JUaLS6BClr/Y1iyzgMdR+uPAO3iOnppYm6Zq3u4D7B/pGQUSGLtyqi+yP7S+zB5z3/4VPeVbA7O+DXRFk3lhrB7Z5NA4FwwS1l5ynpioYEt7XMdiYxn/m7JoMTUQok=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
