travis:
  secure:
    BINSTAR_TOKEN: Us1/YOLgehfIpHLO23Ys5ezuqWkYT0vRQL0CAjhBTAx1xQ0dB5SEEQTmf8UPf1xKz3xdow1DNbtrKh6KDLcevYcGWzkTHJG7K7A9EkNWnUnt69IM6tLCJrfHexBY6PIkdooBQacED6u3qBuH2wBLxsRh+qNo5b7/CkOQwvyn8x3LbPNEqTifShDi7n62xS5AotRbndntmTp+OBHRJqlysyQBLErnNYUT9GB7SvRy/TKA7uPD2M5+YMblXpXevFdPHqzmp79NvFza8pgCJNES5xlNgCcIWVxR+pxQBaAUaqUi0dcYMK4h3vDXGnLtfvY5xG5UqG9dEnGWsjlGCQA2V8ZjtaO3tOIxaHbq+diU0XzgqcJY4cSPrmYKu6dCIz9KhdsshZW5e8GeNRoeSwGoMfppgKteGqUVykAlHDCL+kbrCVg2isJ4+m5YA+gbYzl0rcxjAKgX+t0QvGbkaMiSBmdp175h7haYoP8cYiPZFWHCcO/OBv2T45SUOlyn12zCeHY3akGETKdr9oG2EBebszb2Wo43Cz/DzRDQc8O//FTXC1gP04+9b2XwHKcVzdNkogNghWiJPJ4AMP7xZDZJwPuwpyYzj/rOCQcRhgYdPQcB5dG0X4JG4m1yq3cSH/9+6rlP+TbS9UWumopTBTOtcfY9DXKfcM9p3RCcKmn7Syk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
