appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: lTAC/95/sTe5HpKCKw2yEsLPCHV36Zf4QfWXu46I96LVgWlwxWSTStgjhls1EMdkmgqT6iqeEzYjyge+MOJPTKADgS3N7/RJNtJeLXqOOsgV04SB413qVG8fY2Qcs2u+vddWZljpz+BoqWEpYPBl5doU19zrxdmMafF1VfVmbHvhFY9KbGMvTtqPPqAkSH54oVpjEdytIEzuwZN6ooXuB1VNurWaVF1kiOLBway0w5RtrySGcxxMiRPZ4D1jPI9A5bxovu3FwwOi+Ot44h5OYoULZv7/70hzFgFnTGa+wMs/QOcIFWejODtN/3bw8BNhUYYjDmm9R1gN/Ydd+uGd1JDlJY4ufQqXA74emtx15F6nUJs1YnstCEikmg4aFvNk10NDLuiRtdmT6kL12xoXtPDqc0DPMnXhY+U1Nk87ABSUWH5Pgty9rIV2D9+13XuZkPkr+2uUvCCOZx7wkgDUNZVN0rCJ2eAKJ0Fvjc3MLHbYxHJyV0u0TGNHY+AFqzm/EmNWdzkZuHiloBccKajupnoIr6vnFle4rV0vohMOYB/k2SRc7gnIF8M4rEYBOL1sN1fIoY5Hlpfkxbz2+acCxh4C6WrNCc25N3s4Rg2vv42Dx8XTtvRzMY/gtAV7f13ZtE7HsGHBuXTITRAfyluv+h/6UwtRhKqe6ja6K+x9fEc=}
