travis:
  secure:
    BINSTAR_TOKEN: M9XMfGmkBANmXaqWuTK97T5DU/285Wono4lLJDzIugkD1Z4TpOh3/qU4LiuZ3UkzrMhVE21QIPvnat9thSxD/XJsl1LAM0LACqWMDUJKrk5HEq79F2tb59Cy/PcP2m1eD+fH8bApNKV1pjsbzAkHOXNt7+YWQMu7fWYTabc8RjF9Y4c2NDqOgTiSUXs+pZdZV1lJJxkCVkR2g75RT/TCavzh89lDnmJeq+JmL7ELU/dDGUiwRsT44tMECG/qWHrhmloeSCY/jfafxtbJdtPJaZVLUpSPpL4AbCCeJEmRtMZgv64kygmJ8OQYJR8pNZq6Xb4TLSP6LmwRs5z7dO6NYppNxJWdWLGaASwQvt4f9sNrwfEyms5k0kGPQZPZtJ6VskXnGEhLbNwhHui5i2zRKBeQDLBRcWyyA1O+wDJuw16duXEK+jT1KTMqgAQIdfFdealvCGPlu/RkmKPYJICZ67tYt5+aPf435pjIH83cp5I4fuLFiXK2Mg+d6Isliloruhut2SGjxmRtLKF/6BaYyDg6mgaiDxJ/jIqPv862gJkNqlDGESDv7/TFxeqb3jIe0CuZz2Ab4SS0+nZGu9wybtwQxsm8zyfvGyP4qdrJs7m4+4cXnATZsTrkcdqy2yqbcgTdGFxFLNR9VMcLc6+i6B9y7Pm9ddlaYyvfouME42M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
